# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'RobotWhiteBoardDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  pod 'DoraemonKit/Core', '~> 3.0.2', :configurations => ['Debug'] #必选
  pod 'DoraemonKit/WithLogger', '~> 3.0.2', :configurations => ['Debug'] #可选 

end
